# Generated by Django 3.2.7 on 2021-11-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('times_followed', models.PositiveIntegerField(default=0)),
                ('raw_url', models.URLField()),
                ('downloadable_url', models.CharField(max_length=1000)),
                ('social_media_source', models.CharField(max_length=1000)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
