# Generated by Django 3.2.7 on 2021-09-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parse',
            name='downloadable_url',
            field=models.CharField(max_length=1000),
        ),
    ]
